name: CI/CD Docker Pipeline

on:
  push:
    branches: [ "main" ]  # Tự động chạy khi push code lên nhánh main

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, product, order, api-gateway]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          npm install
      - name: Run tests
        run: |
          cd ${{ matrix.service }}
          npm test

  build-and-push:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code từ GitHub repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Thiết lập Docker Buildx để build đa nền tảng
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Đăng nhập Docker Hub bằng secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build & Push Auth Service
      - name: Build & Push Auth Service
        uses: docker/build-push-action@v6
        with:
          context: ./auth
          file: ./auth/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth_service:latest
          platforms: linux/amd64,linux/arm64

      # 5. Build & Push Product Service
      - name: Build & Push Product Service
        uses: docker/build-push-action@v6
        with:
          context: ./product
          file: ./product/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product_service:latest
          platforms: linux/amd64,linux/arm64

      # 6. Build & Push Order Service
      - name: Build & Push Order Service
        uses: docker/build-push-action@v6
        with:
          context: ./order
          file: ./order/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/order_service:latest
          platforms: linux/amd64,linux/arm64

      # 7. Build & Push API Gateway
      - name: Build & Push API Gateway
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api_gateway:latest
          platforms: linux/amd64,linux/arm64